### ISSUE TITLE
Swapping out react-native-sqlite2 for this implementation using react-native-quick-sqlite causes data to dissapear

### ISSUE THREAD

**Issue by Daniyaalbeg** [craftzdog/react-native-quick-websql#2]
Hey craftzdog!

Love your work, and have been following your stuff for a while. Wanted to get your take on an issue I'm facing and if you had any idea that could point me in the right direction to solve this.

I have an open issue on react-native-quick-sqlite but I am not sure where the problem in my setup lies. Any help would be appreciated.

[https://github.com/ospfranco/react-native-quick-sqlite/issues/72](url)

**Comment by craftzdog** [comment]
Oscar answered the question
