### ISSUE TITLE
Not working with latest version of react-native-quick-sqlite

### ISSUE THREAD

**Issue by panda0603** [craftzdog/react-native-quick-websql#3]
hello, 

it seems like api has been changed with latest version of react-native-quick-sqlite.

`executeSql` has been renamed to `execute`. 

https://github.com/craftzdog/react-native-quick-websql/blob/397cb625abf5795da9027e73c93a79a0d3c20e93/src/sqlite-database.ts#L34

**Comment by craftzdog** [comment]
will look into it next year
